'use client';

import StyledComponentsRegistry from './lib/registry';
import { ThemeProvider } from 'styled-components';

import { GlobalStyles } from '@/common/styles/global';
import { theme } from '@/common/styles/theme';

const RootLayout: React.FC<{ children: React.ReactNode }> = ({ children }) => (
  <html lang="ko">
    <head>
      <title>Create Next App</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </head>
    <body>
      <StyledComponentsRegistry>
        <>
          <GlobalStyles />
          <ThemeProvider theme={theme}>{children}</ThemeProvider>
        </>
      </StyledComponentsRegistry>
    </body>
  </html>
);

export default RootLayout;
